name = "communication-builder-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "TEMPLATES"
id = "6200020dbedc4b4e9ffeeacccf70c8f1"

[ai]
binding = "AI"

[build]
command = ""

[env.production.vars]
ENVIRONMENT = "production"

[env.staging.vars]
ENVIRONMENT = "staging"
